console.log("String to number converstion")
let tc=Number("3.14") 
console.log(tc)
console.log("Converting number to string:")
let tc1=String(10)
console.log(tc1)
console.log("Converting date to number:")
dd = new Date();
console.log(dd)
console.log(Number(dd))
console.log("Converting date to string:")
dd1=new Date()
console.log(String(dd1))
console.log("Converting bool to decimal")
console.log(Number(false))
console.log(Number(true))

